# Generated by Django 3.2.25 on 2025-02-18 11:43

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['number']},
        ),
        migrations.RemoveField(
            model_name='location',
            name='description_long',
        ),
        migrations.RemoveField(
            model_name='location',
            name='description_short',
        ),
        migrations.AddField(
            model_name='location',
            name='long_description',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Длинное описание'),
        ),
        migrations.AddField(
            model_name='location',
            name='short_description',
            field=models.TextField(blank=True, verbose_name='Короткое описание'),
        ),
        migrations.AlterField(
            model_name='image',
            name='location',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='imgs', to='catalog.location'),
        ),
        migrations.AlterField(
            model_name='image',
            name='number',
            field=models.IntegerField(blank=True, default=0, verbose_name='Номер для порядка'),
        ),
        migrations.AlterField(
            model_name='location',
            name='lat',
            field=models.FloatField(verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='location',
            name='lng',
            field=models.FloatField(verbose_name='Долгота'),
        ),
    ]
